addons:
  apt:
    packages:
      - cmake
      - doxygen

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  - clang 

# Build steps

script:
  - curl --fail --silent --remote-time --remote-name --time-cond GeoLite2-City.mmdb "http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz"
  - cmake ${TRAVIS_BUILD_DIR} && make

