addons:
  apt:
    packages:
      - cmake
      - doxygen

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  - clang 

# Build steps
script:
- cmake ${TRAVIS_BUILD_DIR} && make
