addons:
  apt:
    packages:
      - cmake
      - doxygen
      - libmaxminddb-dev

# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  - clang 

# Build steps
before_script:
  - chmod +x ${TRAVIS_BUILD_DIR}/scripts/geolite2pp_get_database.sh
  - ${TRAVIS_BUILD_DIR}/scripts/geolite2pp_get_database.sh

script:
  - cmake ${TRAVIS_BUILD_DIR} && make

